a=int(input("Enter the no: "))
b=int(input("Enter the no: "))
print("Addition of numbers:",a+b)
print("Subtraction of numbers: ",a-b)
print("Division of numbers: ",a/b)
print("Modulus of numbers: ",a%b)
